global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanager_configs:
    - name: 'default'
      alertmanagers:
        - static_configs:
            - targets: []

rule_files: []

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'kiosk_metrics'
    static_configs:
      - targets: ['localhost:8080']