global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanager_configs:
    - name: 'default'
      alertmanagers:
        - static_configs:
            - targets: []

rule_files:
  - 'rules/alerts.yml'

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'firefox_metrics'
    static_configs:
      - targets: ['localhost:9101']

  - job_name: 'homeassistant'
    static_configs:
      - targets: ['localhost:9102']